// Mock data for blood bank management system
export const donors = [
  {
    id: 1,
    name: "Rajesh Kumar",
    bloodType: "O+",
    age: 28,
    location: "Mumbai",
    contactNumber: "9876543210",
    lastDonationDate: "2025-11-15",
    email: "rajesh@gmail.com",
    gender: "Male",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: false,
  },
  {
    id: 2,
    name: "Priya Singh",
    bloodType: "A+",
    age: 32,
    location: "Delhi",
    contactNumber: "9876543211",
    lastDonationDate: "2025-12-01",
    email: "priya@gmail.com",
    gender: "Female",
    recentTattoos: false,
    existingMedications: true,
    chronicIllness: false,
  },
  {
    id: 3,
    name: "Arjun Patel",
    bloodType: "B+",
    age: 25,
    location: "Bangalore",
    contactNumber: "9876543212",
    lastDonationDate: "2025-10-20",
    email: "arjun@gmail.com",
    gender: "Male",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: false,
  },
  {
    id: 4,
    name: "Anjali Verma",
    bloodType: "AB+",
    age: 35,
    location: "Chennai",
    contactNumber: "9876543213",
    lastDonationDate: "2025-09-10",
    email: "anjali@gmail.com",
    gender: "Female",
    recentTattoos: true,
    existingMedications: false,
    chronicIllness: false,
  },
  {
    id: 5,
    name: "Vikram Desai",
    bloodType: "O-",
    age: 30,
    location: "Pune",
    contactNumber: "9876543214",
    lastDonationDate: "2025-12-10",
    email: "vikram@gmail.com",
    gender: "Male",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: false,
  },
  {
    id: 6,
    name: "Neha Gupta",
    bloodType: "A-",
    age: 29,
    location: "Hyderabad",
    contactNumber: "9876543215",
    lastDonationDate: "2025-11-25",
    email: "neha@gmail.com",
    gender: "Female",
    recentTattoos: false,
    existingMedications: true,
    chronicIllness: false,
  },
  {
    id: 7,
    name: "Rohan Sharma",
    bloodType: "B-",
    age: 27,
    location: "Kolkata",
    contactNumber: "9876543216",
    lastDonationDate: "2025-10-05",
    email: "rohan@gmail.com",
    gender: "Male",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: true,
  },
  {
    id: 8,
    name: "Deepika Nair",
    bloodType: "AB-",
    age: 33,
    location: "Kochi",
    contactNumber: "9876543217",
    lastDonationDate: "2025-12-03",
    email: "deepika@gmail.com",
    gender: "Female",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: false,
  },
  {
    id: 9,
    name: "Sanjay Reddy",
    bloodType: "O+",
    age: 40,
    location: "Vizag",
    contactNumber: "9876543218",
    lastDonationDate: "2025-11-18",
    email: "sanjay@gmail.com",
    gender: "Male",
    recentTattoos: false,
    existingMedications: true,
    chronicIllness: false,
  },
  {
    id: 10,
    name: "Pooja Iyer",
    bloodType: "A+",
    age: 26,
    location: "Indore",
    contactNumber: "9876543219",
    lastDonationDate: "2025-12-08",
    email: "pooja@gmail.com",
    gender: "Female",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: false,
  },
  {
    id: 11,
    name: "Nikhil Agarwal",
    bloodType: "B+",
    age: 31,
    location: "Lucknow",
    contactNumber: "9876543220",
    lastDonationDate: "2025-10-30",
    email: "nikhil@gmail.com",
    gender: "Male",
    recentTattoos: true,
    existingMedications: false,
    chronicIllness: false,
  },
  {
    id: 12,
    name: "Divya Singh",
    bloodType: "AB+",
    age: 28,
    location: "Jaipur",
    contactNumber: "9876543221",
    lastDonationDate: "2025-11-20",
    email: "divya@gmail.com",
    gender: "Female",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: false,
  },
  {
    id: 13,
    name: "Aditya Malhotra",
    bloodType: "O-",
    age: 34,
    location: "Chandigarh",
    contactNumber: "9876543222",
    lastDonationDate: "2025-09-15",
    email: "aditya@gmail.com",
    gender: "Male",
    recentTattoos: false,
    existingMedications: true,
    chronicIllness: false,
  },
  {
    id: 14,
    name: "Kavya Menon",
    bloodType: "A-",
    age: 24,
    location: "Thiruvananthapuram",
    contactNumber: "9876543223",
    lastDonationDate: "2025-12-05",
    email: "kavya@gmail.com",
    gender: "Female",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: false,
  },
  {
    id: 15,
    name: "Harish Bhat",
    bloodType: "B-",
    age: 29,
    location: "Mangalore",
    contactNumber: "9876543224",
    lastDonationDate: "2025-11-12",
    email: "harish@gmail.com",
    gender: "Male",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: true,
  },
  {
    id: 16,
    name: "Shreya Bhattacharya",
    bloodType: "AB-",
    age: 27,
    location: "Guwahati",
    contactNumber: "9876543225",
    lastDonationDate: "2025-10-22",
    email: "shreya@gmail.com",
    gender: "Female",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: false,
  },
  {
    id: 17,
    name: "Manish Chopra",
    bloodType: "O+",
    age: 36,
    location: "Vadodara",
    contactNumber: "9876543226",
    lastDonationDate: "2025-12-02",
    email: "manish@gmail.com",
    gender: "Male",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: false,
  },
  {
    id: 18,
    name: "Riya Chatterjee",
    bloodType: "A+",
    age: 25,
    location: "Ahmedabad",
    contactNumber: "9876543227",
    lastDonationDate: "2025-11-28",
    email: "riya@gmail.com",
    gender: "Female",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: false,
  },
  {
    id: 19,
    name: "Amit Sinha",
    bloodType: "B+",
    age: 32,
    location: "Patna",
    contactNumber: "9876543228",
    lastDonationDate: "2025-10-15",
    email: "amit@gmail.com",
    gender: "Male",
    recentTattoos: true,
    existingMedications: true,
    chronicIllness: false,
  },
  {
    id: 20,
    name: "Sneha Roy",
    bloodType: "AB+",
    age: 30,
    location: "Ranchi",
    contactNumber: "9876543229",
    lastDonationDate: "2025-11-30",
    email: "sneha@gmail.com",
    gender: "Female",
    recentTattoos: false,
    existingMedications: false,
    chronicIllness: false,
  },
];

export const recentDonations = [
  {
    id: 101,
    donorName: "Rajesh Kumar",
    bloodType: "O+",
    unitsCollected: 450,
    date: "2025-12-26",
    time: "14:30",
  },
  {
    id: 102,
    donorName: "Priya Singh",
    bloodType: "A+",
    unitsCollected: 450,
    date: "2025-12-25",
    time: "11:15",
  },
  {
    id: 103,
    donorName: "Vikram Desai",
    bloodType: "O-",
    unitsCollected: 450,
    date: "2025-12-24",
    time: "16:45",
  },
  {
    id: 104,
    donorName: "Deepika Nair",
    bloodType: "AB-",
    unitsCollected: 450,
    date: "2025-12-23",
    time: "09:20",
  },
  {
    id: 105,
    donorName: "Pooja Iyer",
    bloodType: "A+",
    unitsCollected: 450,
    date: "2025-12-22",
    time: "15:00",
  },
];

export const bloodInventory = {
  "O+": 45,
  "O-": 12,
  "A+": 28,
  "A-": 8,
  "B+": 35,
  "B-": 5,
  "AB+": 18,
  "AB-": 3,
};

export const stats = {
  totalDonors: 20,
  pendingRequests: 7,
  unitsCollectedToday: 2250,
  totalUnitsInStock: 154,
};
